run:
  concurrency: 4        
  timeout: 5m           
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

output:
  print-issued-lines: true       
  print-linter-name: true        
  sort-results: true             

linters:
 enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

issues:
  exclude-rules:
    - path: .
      linters:
        - lll                
        - exhauststruct     
        - nestif            
        - gocyclo           
        - gci                
        - varnamelen        
        - dupl              
        - wastedassign      
        - forceotypeassert   
        - ireturn

        # ВРЕМЕННО:
        - wsl              
        - err113            
        - wrapcheck        
        - whitespace       

    - path: _test\.go
      linters:               
        - testpackage      
        - funlen           
        - depguard         
        - noGlobal          
        - thelper          
        - gochecknoglobals  
        - cyclop           
        - gocognit
        - containedctx
        - gosimple
        - containedctx
        - errcheck

        # ВРЕМЕННО:
        - wsl                    
        - err113                
        - wrapcheck            

severity:
  default-severity: error   
  rules:
    - severity: info
      linters:
        - forbidigo          
    - severity: error
      linters:
        - govet             
        - staticcheck       
        - errcheck          
        - gocritic          
        - depguard          
        - gosec             
        - deadcode          
        - gosimple          

linters-settings:
  tagging:
    sort: true
  output:
    format:
      - yaml
      - json

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

  gocritic:
    enables-checks:
      - boolExprSimplify
      - emptyStringTest

  lll:
    line-length: 160

  prealloc:
    simple: true

  cyclop:
    max-complexity: 15

  unparam:
    check-exported: true

  staticcheck:
    checks:
     - SA1000
     - SA1001
     - SA1002
     - SA2000
     - SA4010

  govet:
    enable:
      - shadow

  mnd:
   checks:
    - argument
    - case
    - condition
    - return
    - assign
  ignored-numbers:
  - '0o666'
  - '0o644'
  - '0o755'

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        taml: snake
  
  perfsprint:
    errorf: false

  nlreturn:
    block-size: 2
  
  errcheck:
    check-type-assertiongs: true

  funlen:
    ignore-comments: true

  exhaustive:
    default-signifies-exhaustive: true
    default-case-required: false
