name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test -v ./...

      - name: Run linting
        run: |
          go vet ./...
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Create Release
        run: |
          gh release create ${{ github.ref }} \
            --title "Release ${{ github.ref }}" \
            --notes "## Changes in this Release
            
          ### Features
          - Transaction management with commit and rollback support
          - Atomic execution of operations
          - Storage-agnostic design
          
          ### Installation
          \`\`\`bash
          go get github.com/Pizhlo/tx-keeper@${{ github.ref }}
          \`\`\`"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 