name: go vet test

on:
  push:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
    
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.24'
            
        - name: Verify dependencies
          run: go mod verify
    
        - name: Run go vet
          run: go vet ./...

        - name: Install staticcheck
          run: go install honnef.co/go/tools/cmd/staticcheck@latest

        - name: Run staticcheck
          run: staticcheck ./...

    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.24'

          - name: Test
            run: go test -gcflags="-l" -race -v ./...
    